server:
  port: 8097
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bdd_store
    username: postgres
    password: postgres
    jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml
  logging:
    level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    liquibase: INFO
